#
# Copyright (C) 2017 NXP Semiconductors
#
# SPDX-License-Identifier:     BSD-3-Clause
#

.PHONY: all clean

all: ; mpic++ -cxx=g++ main.cpp -std=c++0x -o mpi_demo -pthread

clean: ; rm -rf mpi_demo;

.DEFAULT_GOAL = all