#
# Copyright (C) 2016 NXP Semiconductors
#
# SPDX-License-Identifier:		BSD-3-Clause
#

DEPS	:=	gpio_func.h
SOURCES :=	gpio_func.c\
		gpio_sample.c
OBJ	:=	$(SOURCES:.c=.o)
EXE	:=	gpio

include ../common.mk
