#
# Copyright (C) 2016 NXP Semiconductors
#
# SPDX-License-Identifier:     BSD-3-Clause
#

LDFLAGS		+= -lpthread
EXE		:= multicore
DEPS	:= functions.h
OBJ		:= multicore.o functions.o
INSTALLEXTRA	= *.in

include ../common.mk
