#
# Copyright (C) 2016 NXP Semiconductors
#
# SPDX-License-Identifier:     BSD-3-Clause
#

EXE := server_multiclient server client
OBJ_server_multiclient := server_multiclient.o utils.o
OBJ_server := server.o utils.o
OBJ_client := client.o utils.o

include ../common.mk
